### ISSUE TITLE
OMEMO Issues

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#573]
Tracking issues on the `omemo` branch:
- [x] Your device list gets cleared and replaced by current device (every launch?)
- [x] User Info View Controller #584
  - [x] No way to override between Plaintext/OTR/OMEMO #584 
  - [ ] Better way to share all self/other fingerprints at the same time
- [x] Show placeholder text for input text view to show OTR/OMEMO/Plaintext
- [ ] Show verification screen when new untrusted device appears, before sending message
- [x] Messages need device foreign keys sender and receiver
- [x] Error handling improvements on OMEMO and Signal
- [x] Queue integration #401 
- [X] ~~MAM #399~~ Moved to 4.1 milestone
